// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwGLfxgW2jQrghtlnKfDMQZP1FzZeHTQ',
    appId: '1:1027867807290:web:7c30250a37099f8a0aaf03',
    messagingSenderId: '1027867807290',
    projectId: 'chat-app-44db7',
    authDomain: 'chat-app-44db7.firebaseapp.com',
    storageBucket: 'chat-app-44db7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCHsaP3TQsKKZhxFlQHki-hfrhvkDEos',
    appId: '1:1027867807290:android:f99ad52df0d404180aaf03',
    messagingSenderId: '1027867807290',
    projectId: 'chat-app-44db7',
    storageBucket: 'chat-app-44db7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUOMaHdlh_HYqXYhAwrtXcVYApiN8fPo',
    appId: '1:1027867807290:ios:37fb256bc16b8de80aaf03',
    messagingSenderId: '1027867807290',
    projectId: 'chat-app-44db7',
    storageBucket: 'chat-app-44db7.appspot.com',
    iosClientId: '1027867807290-d61jt2d1mah2s283ks9u43i16gmf7ckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUOMaHdlh_HYqXYhAwrtXcVYApiN8fPo',
    appId: '1:1027867807290:ios:37fb256bc16b8de80aaf03',
    messagingSenderId: '1027867807290',
    projectId: 'chat-app-44db7',
    storageBucket: 'chat-app-44db7.appspot.com',
    iosClientId: '1027867807290-d61jt2d1mah2s283ks9u43i16gmf7ckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
